### ISSUE TITLE
common_modulus_decrypt(c1, c2, key1, key2) needs to check if gcd is 1

### ISSUE THREAD

**Issue by packetmania** [Apress/practical-cryptography-in-python#2]
If gcd is not 1, this function could not get plaintext message correctly. The RSA Common Modulus Attack only works with gcd(e1, e1)=1 case.

**Comment by sethnielson** [comment]
Thanks @packetmania I will update the code soon and put a note in the errata.

**Comment by packetmania** [comment]
Thanks.

**Comment by packetmania** [comment]
Sorry, I accidentally closed it. When will the fix be committed?

**Comment by sethnielson** [comment]
Hi @packetmania, I've been really busy. But I am working on the edits. I have added a GCD==1 check to the function `common_modulus_decrypt`. I'm also working on the errata. Before I commit, let me get your verification on my analysis. When the original e1 value is prime, any smaller value e2 value by definition will have a GCD==1. So, in the example in the book, e1==65537 and e2==3 must be GCD==1. Also, given that the most common e value is 65537, picking any other value, other than a multiple of 65537, would also have a GCD of 1. Do you see any errors in my reasoning? Thanks.

**Comment by packetmania** [comment]
Hi @sethnielson , your reasoning is correct. Thanks.

**Comment by sethnielson** [comment]
@packetmania, would you mind reviewing my pull request associated with the branch sethnielson-rsa-common-modulus-gcd-fix? If you don't have time, I'll merge, but I always like to have another pair or eyes.

**Comment by sethnielson** [comment]
Fixed with the merge of branch sethnielson-rsa-common-modulus-gcd-fix. Thanks @packetmania
