### ISSUE TITLE
Error on page 201

### ISSUE THREAD

**Issue by spak9** [Apress/practical-cryptography-in-python#4]
The following paragraph:
```
The function creates a dictionary and loads three fields: a subject name (identity),
an issuer name, and a public key. Note that there are (parts of) two key pairs being used
in this file. There is an issuer private key and the subject public key. It is the subject’s
private key that is being stored in the certificate. This public key in many ways represents
the subject as it will be used to prove his or her identity. That is why it is so important
that the certificate be signed.10 Otherwise, anyone could create a certificate to claim any
identity they like.
```

I believe you mean to say "It is the subject's public key that is being stored in the certificate", rather than "private key"?
I'm probably wrong!

**Comment by sethnielson** [comment]
Ha ha! You're absolutely right! What an embarrassing mistake! I will update the errata.

**Comment by sethnielson** [comment]
@spak9 would you mind reviewing the proposed errata (https://github.com/Apress/practical-cryptography-in-python/pull/5)? If you think the text is sufficient I will merge.

**Comment by sethnielson** [comment]
Great. Closing!
